apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: my-watchlist
    apps.tanzu.vmware.com/workload-type: web
  name: my-watchlist
spec:
  source:
    git: 
      url: https://github.com/berinle/my-watchlist
      ref:
        branch: master
  build:
    env:
    - name: BP_NODE_VERSION
      value: "12.22.12"
  env:
  - name: BP_NODE_VERSION
    value: "12.22.12"
